apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-demo
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin-demo
  labels:
    app: httpbin
    serviceenv.zaeyi.com/env: canary
spec:
  ports:
  - port: 8000
    name: http
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin-demo
  labels:
    app: httpbin
    serviceenv.zaeyi.com/env: canary
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        serviceenv.zaeyi.com/env: canary
        version: v1
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
